name: semantic-release

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [semantic-release]

jobs:
  release:
    runs-on: ubuntu-16.04
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with: { "node-version": "12.13.x" }
      - run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm ci --ignore-scripts
        env:
          CI: true
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
